name: Compilar EXE e Lançar Versão

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    name: Compilar para Windows
    runs-on: windows-latest

    steps:
      - name: 📥 Baixar o código do repositório
        uses: actions/checkout@v4

      - name: 🐍 Instalar o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 📦 Instalar Bibliotecas e PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: ⚙️ Gerar o Arquivo Executável (.exe)
        run: |
          pyinstaller --noconfirm --onefile --windowed --icon "icone.ico" --add-data "icone.ico;." main.py

      - name: 🏷️ Renomear o executável
        run: |
          cd dist
          ren main.exe "Hub_Automacao.exe"

      - name: 🚀 Anexar o .exe no Release do GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: dist/Hub_Automacao.exe
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}